name: Build and Tag Quai GPU Miner

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag version for the release (e.g., v1.0.0)'
        required: true
      branch:
        description: 'Branch to release from (e.g., main, develop)'
        default: 'main'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CUDA and dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake mesa-common-dev git wget

      - name: Initialize and update submodules
        run: |
          ls ../
          git submodule update --init --recursive

      - name: Build NVIDIA version
        run: |
          mkdir build && cd build
          cmake .. -DETHASHCUDA=OFF -DETHASHCL=ON
          cmake --build .
          mkdir -p ../../output/quai-gpu-miner-nvidia && cp kawpowminer/quai-gpu-miner ../../output/quai-gpu-miner-nvidia/quai-gpu-miner-nvidia

      - name: Package NVIDIA version
        run: |
          cd ../
          cp -r hiveos_packager_nvidia ../output/quai-gpu-miner-nvidia/hiveos_packager_nvidia
          chmod -R a+rwx ../output/quai-gpu-miner-nvidia
          tar -zcvf ../output/quai-gpu-miner-nvidia.tar.gz -C ../output/quai-gpu-miner-nvidia

      - name: Build AMD version
        run: |
          rm -rf build && mkdir build && cd build
          cmake .. -DETHASHCUDA=OFF -DETHASHCL=ON
          cmake --build .
          mkdir -p ../../output/quai-gpu-miner-amd && cp kawpowminer/quai-gpu-miner ../../output/quai-gpu-miner-amd/quai-gpu-miner-amd

      - name: Package AMD version
        run: |
          cd ../
          cp -r hiveos_packager_amd ../output/quai-gpu-miner-amd/hiveos_packager_amd
          chmod -R a+rwx ../output/quai-gpu-miner-amd
          tar -zcvf ../output/quai-gpu-miner-amd.tar.gz -C ../output/quai-gpu-miner-amd


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quai-gpu-miner-artifacts
          path: |
            output/quai-gpu-miner-nvidia.tar.gz
            output/quai-gpu-miner-amd.tar.gz

      - name: Finish
        run: |
          echo "All tasks completed successfully!"
